# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'

target 'GMSSample' do
  pod 'GoogleMaps', '7.4.0'
end
